version: '3.1'
networks: 
  wk-docker-cluster:
    external: true
services:
  zookeeper1:
    image: zookeeper
    hostname: zk1
    networks: 
      wk-docker-cluster:
        ipv4_address: 192.168.0.21
    ports: 
      - 12181:2181
    environment: 
      ZOO_MY_ID: 1
    volumes: 
      - /data/projects/my_projects/dockerfile/zookeeper/zoo-1.cfg:/conf/zoo.cfg
  zookeeper2:
    image: zookeeper
    hostname: zk2
    networks: 
      wk-docker-cluster:
        ipv4_address: 192.168.0.22
    ports: 
      - 22181:2181
    environment: 
      ZOO_MY_ID: 2
    volumes: 
      - /data/projects/my_projects/dockerfile/zookeeper/zoo-2.cfg:/conf/zoo.cfg
    links:
     - zookeeper1:zookeeper 
  zookeeper3:
    image: zookeeper
    hostname: zk2
    networks: 
      wk-docker-cluster:
        ipv4_address: 192.168.0.23
    ports: 
      - 32181:2181
    environment: 
      ZOO_MY_ID: 3
    volumes: 
      - /data/projects/my_projects/dockerfile/zookeeper/zoo-3.cfg:/conf/zoo.cfg
    links:
     - zookeeper1:zookeeper 